image: simgrid/build-deps

stages:
 - build
 - deploy

# On framagit, we only run the tests for merge requests
build-MR:
  stage: build
  only:
  - merge_requests
  except:
  - stable
  script:
  #- apt-get --allow-releaseinfo-change update
  #- apt install -y binutils
  - cmake -Denable_model-checking=ON -Denable_documentation=OFF -Denable_coverage=OFF -Denable_compile_optimizations=ON -Denable_smpi=ON -Denable_testsuite_smpi_MPICH3=ON -Denable_testsuite_McMini=ON -Denable_compile_warnings=ON -DLTO_EXTRA_FLAG="auto" .
  - make -j$(nproc) VERBOSE=1 all tests distcheck-configure
  - ctest -T Test -j$(nproc) --output-junit result.xml --output-on-failure
  artifacts:
    when: always
    expire_in: 6 months
    reports:
      junit: result.xml

# Build the doc and the webpage 
pages:
  stage: deploy
  needs: [] # no dependency
  script:
  - echo "Building the python bindings (the doc needs them)"
  - cmake -Denable_model-checking=OFF -Denable_documentation=OFF -Denable_coverage=OFF -Denable_compile_optimizations=OFF -Denable_smpi=ON .
  - make -j$(nproc) VERBOSE=1 python-bindings

  - echo "Building the doc"
  - apt install -y python3-breathe python3-sphinx python3-sphinx-rtd-theme python3-sphinx-copybutton python3-sphinx-tabs
  - cd docs
  - LC_ALL=C.UTF-8 ./Build.sh
  - mv build/html ../public
  # - The CSS contains a reference to a font or something, not something we gonna fix on our side
# not installed   - linkchecker --ignore-url='.*\.css$' ../public
  # From time to time, we should check external links with the
  # following, but it has a lot of false positive
  # - linkchecker --ignore-url='.*\.css$' --check-extern ../public
  artifacts:
    paths:
    - public
  only:
  - master

# Build a valid tar.gz
release-tgz:
  stage: build
  only:
  - stable
  script:
  - apt-get --allow-releaseinfo-change update
  - apt install -y binutils wget unzip zip
  - cmake -Denable_documentation=OFF -Dminimal-bindings=ON -Denable_compile_optimizations=ON -Denable_smpi=OFF -DLTO_EXTRA_FLAG="auto" .
  - make VERBOSE=1 -j$(nproc) dist
  artifacts:
    paths:
    - simgrid-*.tar.gz
